-- MySQL Script generated by MySQL Workbench
-- Thu Nov 11 17:32:48 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BSS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Recomendar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Recomendar` ;

CREATE TABLE IF NOT EXISTS `Recomendar` (
  `Usuario_Nome` VARCHAR(45) NOT NULL DEFAULT 'XXXXXXXXX',
  `Sites_URL` VARCHAR(45) NOT NULL DEFAULT 'https://aaaaaaaa.com',
  `Seguro` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`Usuario_Nome`, `Sites_URL`),
  CONSTRAINT `FK_Sites_Usuario`
    FOREIGN KEY (`Usuario_Nome`)
    REFERENCES `Usuario` (`Nome`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Usuario_Sites`
    FOREIGN KEY (`Sites_URL`)
    REFERENCES `Sites` (`URL`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_Usuario_has_Sites_Sites1_idx` ON `Recomendar` (`Sites_URL` ASC) VISIBLE;

CREATE INDEX `fk_Usuario_has_Sites_Usuario_idx` ON `Recomendar` (`Usuario_Nome` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Sites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sites` ;

CREATE TABLE IF NOT EXISTS `Sites` (
  `URL` VARCHAR(45) NOT NULL DEFAULT 'https://aaaaaaaa.com',
  `Nome` VARCHAR(45) NOT NULL DEFAULT 'ZZZZZZZZZ',
  PRIMARY KEY (`URL`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `URL_UNIQUE` ON `Sites` (`URL` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuario` ;

CREATE TABLE IF NOT EXISTS `Usuario` (
  `Nome` VARCHAR(45) NOT NULL DEFAULT 'XXXXXXXXX',
  `Senha` VARCHAR(45) NOT NULL DEFAULT 'SSSSSSSSS',
  `Email` VARCHAR(45) NOT NULL DEFAULT 'xxxxxx@gmail.com',
  PRIMARY KEY (`Nome`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `Email_UNIQUE` ON `Usuario` (`Email` ASC) VISIBLE;

CREATE UNIQUE INDEX `Nome_UNIQUE` ON `Usuario` (`Nome` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
